sudo: required    # need super user level permission

services:
  - docker    # Install a copy of docker into our little running container.

befor_install:
  - docker build -t tohid1987/docker-react -f Dockerfile.dev .   # before do anything build an image

script:   # contain all the different commands that need to be executed to actually run our test suite.
  - docker run tohid1987/docker-react npm run test -- --coverage  # coverage used to exit after test done
  
