version: '3'
services:
  web:
    build:                                # Refer to Dockerfile created for image
      context: .                          # Specify where we want all the files and folders for this image to be pulled from
      dockerfile: Dockerfile.dev          # Use file to build the image
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules                 # Do not try to map a folder up against node_modules
      - .:/app                            # Map the current folder that contain source code to app folder inside container
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]    #used to override npm run start with npm run test